### ISSUE TITLE
region maps for the main areas of the homepage

### ISSUE THREAD

**Issue by Plebster** [Blushtones/testing#2]
region maps required for the homepage areas(header, footer, content....)

**Comment by caprenter** [comment]
I think the site might make this a bit harder for because of the lake if css id's.

The Footer is actually a pre-footer block with the Donate, Social Media and Weather items
and then the 'footer' section itself.

The header html tag has an id in it, but I think that's all.

Within the footer area (tag) the bottom menu has an id

**Comment by Plebster** [comment]
I've managed to split this and put it on the wiki, this is going to be the first thing I try to implement using submodules if I can...

http://wiki.jimatkinson.co.uk/index.php/Testing_Examples

**Comment by caprenter** [comment]
Re-opening- I could have created a new issue, but I think it's ok to reopen this.
The region map needs tidying up - my_content and latest_news are redundant now.

Also I think that some of the home page regions that have been created are not home page specific - header,footer,pre-footer, content. 

Will commit a change for consideration

**Comment by caprenter** [comment]
The above commit https://github.com/Blushtones/testing/commit/0845a4b8108b23cbce37b9fc77eaf28a08df4238 suggests a change to your regions @Plebster - see what you think

**Comment by Plebster** [comment]
good idea
