### ISSUE TITLE
how to use this repository in(with) another GitHub repository

### ISSUE THREAD

**Issue by Plebster** [Blushtones/testing#3]
not sure how to do this, maybe overthinking it @caprenter

**Comment by caprenter** [comment]
Yeah - my plan for this is:

Clone this repo to my machine somewhere
Use symlinks from the 'working behat vendor directory' to run them - do you think that will work?

I think ultimately we're hoping to Create a Standalone testing docker? See #16

**Comment by Plebster** [comment]
I don't like the idea of working with symlinks but can't articulate why at the minute without trying it out...

My initial thoughts would not be to have a standalone testing environment as each site is too nuanced, just looking at your test issues shows that. Again, once I have tested more than one site my thoughts might change

**Comment by caprenter** [comment]
Cool - I'm hoping you can find a solution for us!

**Comment by Plebster** [comment]
as you say submodules seems like a winner... I'm going to see if I can get my head around it... seems a bit more fancier than symlinks

**Comment by Plebster** [comment]
https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container

**Comment by Plebster** [comment]
So... Maybe this can be closed... the solution seems to be a bit of both.

here is my history:
` docker compose down`
 `cd docker-compose/drupal/<project_folder>`
  `git submodule add https://github.com/Blushtones/testing.git`
  `docker-compose up -d`
  `docker exec -it -w /var/www/<project_folder> drupal bash`
  `rm behat.yml`
  `rm -R ./features`	
  `ln -s ./testing/behat.yml behat.yml`
  `ln -s ./testing/features/ .`
  `vendor/bin/behat`

these symlinks can prob be committed to the docker repo... not sure about the other testing folder... I think GitHub ignores it... there could be problems in the future with commit codes... I've run out of knowledge at the minute

https://www.youtube.com/watch?v=eJrh5IjWSGM

**Comment by Plebster** [comment]
so... I don't think submodules are the answer as it doesn't seem to allow branches @caprenter can you have a play? If this doesn't work can we just pull the repo as normal into a sub directory and add this to the .gitignoire in the project file?

**Comment by caprenter** [comment]
I'm going to have a go in the next hour to see where i get to.

Wondering if a behat docker running at the same time magically connects
everything up - but does that still give me the 'hard to push issue'
(although that might just mean using a password to push?

I'll see how this goes..

**Comment by caprenter** [comment]
Ok....  (TL;DR is Docker Volumes the answer!)

So I've ignored the submodule thing and just plain cloned the repo as suggested in https://github.com/Blushtones/testing/issues/3#issuecomment-995803319

This is pretty good - it's getting better, but...

All the files are not owned by my git user, but by 'root' - so to open them in an editor I need to run e.g. geany as root.
I'd prefer to run it normally.

I also have to git clone with HTTP -  because the project files on my local machine need 'sudo' to work with, I can't git clone (with SSH) into that working directory (unless I set up SSH keys for root - but that's ...)

Next - if you want to push to this repo and you have cloned it using HTTPS you need to authenticate with a '[personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)'

I think SSH keys is a much better way (personal access tokens should be set to expire quickly) - but they are not set up in the container etc

So all in all.... I guess I really want to access these files just locally - is docker volumes the answer?

**Comment by Plebster** [comment]
Here's a working solution on Mac please test on Linux:

On host machine:

`cd docker-compose/drupal/<project_file>`
`mkdir testing`
`cd testing`
`git clone git@github.com:Blushtones/testing.git .`
`git checkout -b <branch_name>`
`docker-compose up -d`
`docker exec -it -w /var/www/lamrt.org.uk drupal bash`

in docker container:

`rm behat.yml`
`rm -R ./features`
`ln -s ./testing/behat.yml behat.yml`
`ln -s ./testing/features/ .`
`vendor/bin/behat`

On host machine edit files etc:

`git commit -a -m <message_including_issue_number>`
`git push origin <branch_name>`


Check gitHub :D

**Comment by caprenter** [comment]
This is pretty much exactly how I was hoping it work. Good stuff

I think this will still mean I have to work out local permissions for me -
but I think that is the answer.

Is there another task from this to add this to our vanilla install notes?
Can some of it go in the docker file?

Thanks!

**Comment by Plebster** [comment]
I guess if testing is moved into vanilla then yes, otherwise maybe in the testing instructions

www-data seems to be the obvious difference to your set up than mine

**Comment by caprenter** [comment]
So yeah, permissions was the issue. 
I have to untar the archive files (to get started) as root, so that's the default ownership - by changing them to be owned by the local user, it still seems to work in the container, and I can then git clone using ssh and all is good - yeay!

Thanks.

I'm adding the documentation label, and will assign  to me and I'll add to the wiki.
May kick it back to you to look at the vanilla aspect later

**Comment by caprenter** [comment]
Added to the wiki
